### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by Ra2fat** [nishad/udemy-dl-windows#112]
I get this error 
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590
)
when trying to use the tool in cmd with the command:
udemy-dl.exe -u ra2fat-abo-rami@hotmail.com -p password https://www.udemy.com/learn-to-program-with-java-2
How can i solve this?

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.

**Comment by Ra2fat** [comment]
Can you reopen this issue. I added the version number.
Thank you!
