### ISSUE TITLE
 [BUG]: Access is Denied

### ISSUE THREAD

**Issue by agarDev** [nishad/udemy-dl-windows#114]
[BUG]: Access is Denied
Please update the documentation if something is missing or any dependencies need to be resolved.

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
