### ISSUE TITLE
expected quality not found.

### ISSUE THREAD

**Issue by pinku-4132** [nishad/udemy-dl-windows#149]
Hi Nishad,
will we be getting any fix to this  critical issue,expected quality not found?
I am just keep coming to this hub everyday expecting for a fix.

Thank you,

**Comment by eventgenius** [comment]
Same problem here. Any suggestions?

**Comment by zhedongzheng** [comment]
+1 for future fix

**Comment by Nasser-allah** [comment]
Same here

**Comment by linuxbashtard** [comment]
Same here.This is an issue on Ubuntu as well as on Windows. This used to be one of the greatest programs ever. I don't know... Either way, I'm done. Good luck to you all.

**Comment by pythondx** [comment]
guys use youtube-d instead of udemy-dl
it will download videos but will not sort them

**Comment by CaptainMalzbier** [comment]
https://github.com/nishad/udemy-dl-windows/issues/143#issuecomment-303875024

**Comment by linuxbashtard** [comment]
@CaptainMalzbier , I'm pretty familiar with all of these programs, and I did run youtube-dl on linux installed via pip. Youtube-dl, as always, works on pretty much any site you throw at it. However, Udemy seems to be a special case. I haven't been able to download one single video from any course. I have 2 paid courses. Thanks for the heads up though.

**Comment by CaptainMalzbier** [comment]
If you have a working installation of youtube-dl then just open your terminal and type in 
`youtube-dl https://www.udemy.com/COURSENAME -u USERNAME -p PASSWORD`

what does it say?

**Comment by Atomixm** [comment]
@CaptainMalzbier nice tip  it really works , do you know some way in which i could download the extra files included too?

**Comment by Atomixm** [comment]
like png , docx , rar,etc.

**Comment by bilalbayasut** [comment]
same problem here... exactly same problem, any solution ?

**Comment by toeknee581** [comment]
I'm not sure why the owner is not updating the exe, but the code in the repository DOES work, you just have to build the EXE yourself.  My instructions for how to do that are below.

First, I noticed that he bug has been fixed and committed, but the binary (.exe) has not been updated in the dist. Someone in another thread was asking how to build it yourself.

Download Python 2.7.13 from python.org. If you use the installer it will set up the path for you
Use PIP (which was installed with Python) at a command prompt to install PyInstaller with command "pip install pyinstaller"
Install the other required libraries the same way. These are listed in requirements.txt. Commands:
pip install requests==2.9.1
pip install unicode-slugify
pip install colorlog[windows]==2.7.0
pip install future==0.15.2
pip install colorama
in the master folder, you will see a file called udemy-dl.spec. One edit needs to be made to the third line. Make it hiddenimports=["requests"], (or you will get an error when you run it about the requests module not being found)
edit the udemy-dl.py file in the src directory. around line 19 with the other imports, add "import json"
go back to the main folder with the .spec file and use the command "pyinstaller udemy-dl.spec" which will build the executable. I noticed sometimes that I had to delete the .exe from the dist folder for it to update.
Your shiny new exe should now exist in your dist folder and it should work!

CoderTonyB

**Comment by toeknee581** [comment]
I have forked this repo and included an updated exe in the dist folder.  nishad won't mind me posthing this here since he doesn't seem to have the time to update the exe.  I understand this as this is s volunteer project, but folks need help too -

[https://github.com/toeknee581/udemy-dl-windows](https://github.com/toeknee581/udemy-dl-windows)

**Comment by nishad** [comment]
@toeknee581 you are always welcome to fork, create your own distribution and post your project links here. However posting links to external binary files are not something you should do.

**Comment by CaptainMalzbier** [comment]
@Atomixm
I've purchased only one course yet and that one had one archive for every of the 9 chapters which I downloaded manually.

Maybe there's an option to do this via udemy-dl but I didn't have the time to try it yet. I will post it here if I'll find a solution.

**Comment by christerjohansson** [comment]
@CaptainMalzbier Thanx for the tip! the Youtube-dl works fine! 
I used following command in _**Windows 10**_,

`youtube-dl https://www.udemy.com/COURSENAME -u USERNAME -p PASSWORD -o %(chapter_number)s/%(playlist_index)s-%(title)s.%(ext)s` 

It connects to Udemy, and downloads my course into section folders with numbers and names, neatly organized.

Plus Youtube-dl has a ton of other features available.

**Comment by jules-rose** [comment]
Any idea how can I download attached files and quizzes from udemy using youtube-dl ?

**Comment by jules-rose** [comment]
@toeknee581 

I tried downloading udemy course using udemy-dl master file from your link. Glad its able to download videos without any issues, but its getting stuck downloading attached files. Not sure why

Kindly find the screen messages -

Downloading attached files

[ERROR-56] Traceback (most recent call last):
  File "udemy_dl.py", line 906, in <module>
  File "udemy_dl.py", line 903, in main
  File "udemy_dl.py", line 762, in udemy_dl
  File "udemy_dl.py", line 680, in get_data
  File "udemy_dl.py", line 560, in get_attached_file
  File "udemy_dl.py", line 86, in get
  File "site-packages\requests\sessions.py", line 480, in get
  File "site-packages\requests\sessions.py", line 468, in request
  File "site-packages\requests\sessions.py", line 576, in send
  File "site-packages\requests\adapters.py", line 426, in send
ConnectionError: ('Connection aborted.', error(10060, 'A connection attempt fail
ed because the connected party did not properly respond after a period of time,
or established connection failed because connected host has failed to respond'))

None
Failed to execute script udemy_dl

**Comment by christerjohansson** [comment]
@jules-rose You can not download quizzes, as they are a dynamic feature of Udemy.com. As for attachments, Youtube-dl is mainly aimed at downloading Youtube-videos. There are no attachments on Youtube, so the answer is no.

The settings I provided downloads maximum quality video for all files, If you want lower quality you'll have to tell it to do so. Please visit the Youtube-dl documentation and Git for more information on how to do so. It's called 'format' in options.

**Comment by noph34r** [comment]
@christerjohansson 
so i cant download any other attachment from udemy?
i'm able to mix it with aria2, is it possible to download attachment?

i used to use udemy-dl, but cant get it right.. so i need alternative
jdownloader are able to dwnload, but there's no option for sorting based on playlist sadly

**Comment by christerjohansson** [comment]
@noph34r You can always download them manually. I don't know about any other software for downloading Udemy. Also note that Udemy does NOT allow for downloading of content, unless the author specifically allowed it. It's about the whole design and business model of Udemy, you are not suppose to download the content. But rather watch it online through their website or mobile app.

Feel free to combine jdownloader with Youtube-dl, download all videos through Youtube-dl and the attachments through jDownloader. They are both based on the "scraping" technique.

**Comment by noph34r** [comment]
@christerjohansson 
i see,  thanks
at least i can download the videos

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
