### ISSUE TITLE
Cannot Download last files / lectures

### ISSUE THREAD

**Issue by Rishabh-Ahuja** [nishad/udemy-dl-windows#152]
Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 745, in udemy_dl
  File "<string>", line 663, in get_data
  File "<string>", line 562, in get_attached_file
  File "<string>", line 623, in check_downloaded
WindowsError: [Error 3] The system cannot find the path specified
None
udemy_dl returned -1

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
