### ISSUE TITLE
Error: Couldn't fetch token!

### ISSUE THREAD

**Issue by naseem-essa** [nishad/udemy-dl-windows#36]
Hi. When using udemy-dl, i get the error Couldn't fetch token!. What does this mean and how can I fix it. PS-pls take a look at my email. My email address is naseemessa10@gmail.com

**Comment by hiennguyen82** [comment]
hey fucking you,. i telling you stop spam my email. STOP SEND YOUR MESSENGE
TO MY EMAIL.
STOP. YOUR FUCKING NOISY.

2016-01-16 20:39 GMT+07:00 naseem-essa <notifications@github.com>:

**Comment by naseem-essa** [comment]
pardon me, but who are u? are u gaganpreet.arora@gmail.com ? if so, i am truly sorry but i have only sent one email to u in my life. No spam. Nothing. Just a normal email. If u are not gaganpreet.arora@gmail.com, then i only have ppl that i know in my  gmail contacts and sent mail, so u must be mistaking me for someone else, cos i have never heard/seen u every before.

**Comment by nishad** [comment]
@hiennguyen82, nobody is spamming you. You enrolled yourself to watch this project, and you are following it. You can login to GitHub and unsubscribe from the updates from this link https://github.com/nishad/udemy-dl-windows/subscription.

This is a public project, so please behave yourself.

**Comment by naseem-essa** [comment]
tnx nishad for explaining to him that i wasn't spamming any1. the couldn't fetch token error was becos i used details that i had already used b4 to preview the course. nishad, have u thought of making a GUI for ur amazing udemy-dl? is it possible to use https://github.com/chriskiehl/Gooey to achieve this? Looking forward to ur response!

**Comment by nishad** [comment]
This project is a Windows version of https://github.com/nishad/udemy-dl. Windows standalone binaries are provided to help Windows users to avoid the pain of installing Python and all dependencies. Which also helps basic users from debugging python related issues. Along with that the source of this tool is a simple python script, instead of the package approach of `udemy-dl`. That is being used as a standalone script by many non Windows users as well.

`udemy-dl` follows the same pattern of tools in its family, like `youtube-dl`, `coursera-dl` and `edx-dl`. A console application got its own advantages. Along with that all these tools follows [PEP0020](https://www.python.org/dev/peps/pep-0020/), as a practical guideline.

Bloating this simple scripts with more dependencies like `wx-python` (which gooey is build on top of) arises a lot of security and technical risks.
