### ISSUE TITLE
track back most recent call back

### ISSUE THREAD

**Issue by surajy** [nishad/udemy-dl-windows#39]
![udemy](https://cloud.githubusercontent.com/assets/16743146/12419724/ef224a0c-bedd-11e5-94a0-ae2cc734d1fb.png)
![udemy1](https://cloud.githubusercontent.com/assets/16743146/12419725/ef250652-bedd-11e5-8bea-bcd09d4407e2.png)

getting this error can you help

**Comment by naseem-essa** [comment]
the second image error is caused because you need to use the 'cd' command to point towards the file in which udemy-dl.exe is located.follow these steps to fix this error

1. open command prompt
2.enter 'cd C:\Users\ADMIN\THE-FOLDER-IN-WHICH-UDEMY-DL.EXE-IS'.
3.now use udemy-dl.exe https://udemy.com/COURSE_NAME

It should work this time.

The first error is caused because u were using udemy-dl.PY rather than udemy-dl.EXE, Udemy-dl.exe is used for windows instead of udemy-dl.py, as .py requires python extensions to be installed, for it to work.

**Comment by naseem-essa** [comment]
u need to download udemy-dl from this link btw, https://github.com/nishad/udemy-dl-windows/releases/latest. The download as zip file will download the source code, which i doubt u need

**Comment by surajy** [comment]
not working error to download vedio 
anyone one know how to fix this error
![udemy2](https://cloud.githubusercontent.com/assets/16743146/12426180/80c0c1a8-befe-11e5-9be8-7215f5e7dc7b.png)

**Comment by naseem-essa** [comment]
@surajy enter your pssword, then start course preview or enter course, and then press enter
hope, i helped!

**Comment by surajy** [comment]
thx for info,
but not working downloading error
