### ISSUE TITLE
failed to get course id

### ISSUE THREAD

**Issue by madmax2** [nishad/udemy-dl-windows#4]
Not currently working

Get error

-failed to get course id

**Comment by nishad** [comment]
Which version you are using ?
udemy-dl.exe -v will give you the current version. Latest release is 1.8.0.

**Comment by madmax2** [comment]
I just updated to version 1.80 and now it works...

Are you going to be the official to developer this program now that the other one (https://github.com/gaganpreet/udemy-dl) is dead?

And is this official place to get updates now?
-https://github.com/nishad/udemy-dl
-https://github.com/nishad/udemy-dl-windows

Can you implement downloading of course materials?
e.g. PDF files

I know (https://github.com/coursera-dl/coursera-dl) can download course materials..

The author told me, he used beautiful soup to do it, 
If u look a the source code, then u can implement something similar to udemy-dl.

What do u think about doing this in next version of udemy-dl?

**Comment by nishad** [comment]
Right now I don't have any plans to implement any new features. Since the original udemy-dl was taken down with DMCA, I'm supporting existing users with fixes. I personally doesn't use this script. I'll only provide bug fixes for a time being, as I believe udemy-dl script doesn't infringe any udemy.com copyrights.

**Comment by VincyLouis** [comment]
Just want to say thank you for maintaining this software, as the old veresion (https://github.com/gaganpreet/udemy-dl) no longer working.
