### ISSUE TITLE
Handling additional files (non video)

### ISSUE THREAD

**Issue by duracell** [nishad/udemy-dl-windows#6]
Hi, is there any possibilty to download the text documents and other files, too?
As far as I see, only video-files are being downloaded and the numbers are in sequence even if there is another file between two movie files. Is there any possibility to handle this?

**Comment by nishad** [comment]
Right now I don't have any plans to implement this feature. Since the original udemy-dl was taken down with DMCA, I'm supporting existing users with fixes. I personally doesn't use this script. I'll just provide only bug fixes for a time being, as I believe udemy-dl script doesn't infringe any udemy.com copyrights.
