### ISSUE TITLE
I have problems when downloading a course with version 2.1.1 "Not a downloadable course."

### ISSUE THREAD

**Issue by developerco** [nishad/udemy-dl-windows#92]
I have problems when downloading a course with version 2.1.1

I place:

Udemy-DL.EXE user@domain.com -u -p $ ecRe7w0rd https://www.udemy.com/COURSE_NAME

Comes out..

[INFO-127] Trying to log in ...
[INFO-157] Login success.
[INFO-189] Found course id: 795278
[ERROR-686] Not a downloadable course.

Any suggestions? I have to buy the course? or just the preview?

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.

**Comment by developerco** [comment]
I do not understand , as is the format of the publication ?
